name: Job set up
description: Sets up the Java and Gradle
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
